import { Employee } from "../interfaces";

const employeesDummyData: Array<Employee> = [
	{
		employee_id: 0,
		image_name: "/src/assets/images/employees/lois-walker.jpg",
		name: "Lois Walker",
		email: "lois.walker@hotmail.com",
		phone_number: "580-299-5900",
		role: "Junior software engineer",
		employment_type: "full-time",
		salary: 65000,
		remote: 0,
	},
	{
		employee_id: 1,
		image_name: "/src/assets/images/employees/joe-robinson.jpg",
		name: "Joe Robinson",
		email: "joe.robinson@gmail.com",
		phone_number: "334-423-2075",
		role: "Security Specialist",
		employment_type: "full-time",
		salary: 90000,
		remote: 0,
	},
	{
		employee_id: 2,
		image_name: "/src/assets/images/employees/benjamin-russell.jpg",
		name: "Benjamin Russell",
		email: "benjamin.russell@charter.net",
		phone_number: "210-718-8543",
		role: "Web designer",
		employment_type: "full-time",
		salary: 45000,
		remote: 0,
	},
	{
		employee_id: 3,
		image_name: "/src/assets/images/employees/patrick-bailey.jpg",
		name: "Patrick Bailey",
		email: "patrick.bailey@aol.com",
		phone_number: "785-696-3386",
		role: "Junior front-end engineer",
		employment_type: "full-time",
		salary: 70000,
		remote: 0,
	},
	{
		employee_id: 4,
		image_name: "/src/assets/images/employees/carol-murphy.jpg",
		name: "Carol Murphy",
		email: "carol.murphy@gmail.com",
		phone_number: "650-364-2757",
		role: "Mobile app developer",
		employment_type: "full-time",
		salary: 110000,
		remote: 1,
	},
	{
		employee_id: 5,
		image_name: "/src/assets/images/employees/ralph-flores.jpg",
		name: "Ralph Flores",
		email: "ralph.flores@yahoo.com",
		phone_number: "402-996-8546",
		role: "DevOps engineer",
		employment_type: "full-time",
		salary: 65000,
		remote: 1,
	},
	{
		employee_id: 6,
		image_name: "/src/assets/images/employees/jack-alexander.jpg",
		name: "Jack Alexander",
		email: "jack.alexander@gmail.com",
		phone_number: "847-652-0746",
		role: "Technical Lead",
		employment_type: "full-time",
		salary: 120000,
		remote: 0,
	},
	{
		employee_id: 7,
		image_name: "/src/assets/images/employees/wayne-watson.jpg",
		name: "Wayne Watson",
		email: "wayne.watson@gmail.com",
		phone_number: "518-566-5865",
		role: "Data scientist",
		employment_type: "full-time",
		salary: 50000,
		remote: 0,
	},
	{
		employee_id: 8,
		image_name: "/src/assets/images/employees/joshua-stewart.jpg",
		name: "Joshua Stewart",
		email: "joshua.stewart@yahoo.ca",
		phone_number: "605-528-1618",
		role: "Accessibility specialist",
		employment_type: "full-time",
		salary: 34000,
		remote: 1,
	},
	{
		employee_id: 9,
		image_name: "/src/assets/images/employees/thomas-lewis.jpg",
		name: "Thomas Lewis",
		email: "thomas.lewis@gmail.com",
		phone_number: "347-522-2976",
		role: "Database administrator",
		employment_type: "full-time",
		salary: 48000,
		remote: 0,
	},
];

export { employeesDummyData };
