import { HIRING_PROCESS } from "../constants";
import { Candidate } from "../interfaces";

const candidatesDummyData: Array<Candidate> = [
	{
		candidate_id: 0,
		image_name: "/assets/images/employees/lois-walker.jpg",
		name: "Lois Walker",
		email: "lois.walker@hotmail.com",
		phone_number: "580-299-5900",
		applied_role: "Junior software engineer",
		experience: 2,
		employment_type: "full-time",
		current_stage: HIRING_PROCESS[0][1],
		current_role: "Junior software engineer",
		isAccepted: null,
	},
	{
		candidate_id: 1,
		image_name: "/assets/images/employees/joe-robinson.jpg",
		name: "Joe Robinson",
		email: "joe.robinson@gmail.com",
		phone_number: "334-423-2075",
		applied_role: "Security Specialist",
		experience: 1,
		employment_type: "full-time",
		current_stage: HIRING_PROCESS[3][1],
		current_role: "Security Specialist",
		isAccepted: null,
	},
	{
		candidate_id: 2,
		image_name: "/assets/images/employees/benjamin-russell.jpg",
		name: "Benjamin Russell",
		email: "benjamin.russell@charter.net",
		phone_number: "210-718-8543",
		applied_role: "Web designer",
		experience: 3,
		employment_type: "full-time",
		current_stage: HIRING_PROCESS[4][1],
		current_role: "Web designer",
		isAccepted: true,
	},
	{
		candidate_id: 3,
		image_name: "/assets/images/employees/patrick-bailey.jpg",
		name: "Patrick Bailey",
		email: "patrick.bailey@aol.com",
		phone_number: "785-696-3386",
		applied_role: "Junior front-end engineer",
		experience: 1,
		employment_type: "full-time",
		current_stage: HIRING_PROCESS[2][1],
		current_role: "Junior front-end engineer",
		isAccepted: null,
	},
	{
		candidate_id: 4,
		image_name: "/assets/images/employees/carol-murphy.jpg",
		name: "Carol Murphy",
		email: "carol.murphy@gmail.com",
		phone_number: "650-364-2757",
		applied_role: "Mobile app developer",
		experience: 4,
		employment_type: "full-time",
		current_stage: HIRING_PROCESS[2][1],
		current_role: "Mobile app developer",
		isAccepted: false,
	},
	{
		candidate_id: 5,
		image_name: "/assets/images/employees/ralph-flores.jpg",
		name: "Ralph Flores",
		email: "ralph.flores@yahoo.com",
		phone_number: "402-996-8546",
		applied_role: "DevOps engineer",
		experience: 3,
		employment_type: "full-time",
		current_stage: HIRING_PROCESS[2][1],
		current_role: "DevOps engineer",
		isAccepted: null,
	},
	{
		candidate_id: 6,
		image_name: "/assets/images/employees/jack-alexander.jpg",
		name: "Jack Alexander",
		email: "jack.alexander@gmail.com",
		phone_number: "847-652-0746",
		applied_role: "Technical Lead",
		experience: 8,
		employment_type: "full-time",
		current_stage: HIRING_PROCESS[0][1],
		current_role: "Technical Lead",
		isAccepted: null,
	},
	{
		candidate_id: 7,
		image_name: "/assets/images/employees/wayne-watson.jpg",
		name: "Wayne Watson",
		email: "wayne.watson@gmail.com",
		phone_number: "518-566-5865",
		applied_role: "Data scientist",
		experience: 3,
		employment_type: "full-time",
		current_stage: HIRING_PROCESS[0][1],
		current_role: "Data scientist",
		isAccepted: null,
	},
	{
		candidate_id: 8,
		image_name: "/assets/images/employees/joshua-stewart.jpg",
		name: "Joshua Stewart",
		email: "joshua.stewart@yahoo.ca",
		phone_number: "605-528-1618",
		applied_role: "Accessibility specialist",
		experience: 2,
		employment_type: "full-time",
		current_stage: HIRING_PROCESS[3][1],
		current_role: "Accessibility specialist",
		isAccepted: null,
	},
	{
		candidate_id: 9,
		image_name: "/assets/images/employees/thomas-lewis.jpg",
		name: "Thomas Lewis",
		email: "thomas.lewis@gmail.com",
		phone_number: "347-522-2976",
		applied_role: "Database administrator",
		experience: 5,
		employment_type: "full-time",
		current_stage: HIRING_PROCESS[1][1],
		current_role: "Database administrator",
		isAccepted: null,
	},
];

export { candidatesDummyData };
